import React, { useState, useEffect } from 'react';
import { Activity, Sparkles, Server, Info, FileText, AlertTriangle, Palette } from 'lucide-react';
import './Header.css';

type HeaderProps = {
  imageId: string | null;
};

const THEMES = ["light", "dark", "blue", "synthwave"];

const Header: React.FC<HeaderProps> = ({ imageId }) => {
  const [activeModal, setActiveModal] = useState<string | null>(null);
  const [currentTheme, setCurrentTheme] = useState(THEMES[0]);

  useEffect(() => {
    document.body.setAttribute('data-theme', currentTheme);
  }, [currentTheme]);

  const renderModal = () => {
    if (!activeModal) return null;

    const modals: { [key: string]: { title: string; content: React.ReactNode } } = {
      about: {
        title: 'About Rad-VQA',
        content: (
          <p>
            Rad-VQA is an AI-powered assistant for medical imaging analysis. 
            Upload a medical scan, and ask questions to get insights. 
            This tool is for research purposes only and not for clinical use.
          </p>
        ),
      },
      docs: {
        title: 'Documentation',
        content: (
          <>
            <p><strong>How to use:</strong></p>
            <ol>
              <li>Upload an image (JPG, PNG).</li>
              <li>Wait for the "Connected to Context" status.</li>
              <li>Ask questions about the image in the chat window.</li>
            </ol>
            <p><strong>Model Strengths:</strong> The model is best at answering questions about the presence, location, and attributes of findings in the image.</p>
          </>
        ),
      },
      warnings: {
        title: 'Warnings',
        content: (
          <p>
            <strong>NOT FOR CLINICAL USE.</strong> The responses from this model are generated by an AI and may be inaccurate. 
            Do not use this tool for medical diagnosis or treatment decisions. 
            Always consult a qualified medical professional.
          </p>
        ),
      },
    };

    const modal = modals[activeModal];

    return (
      <div className="modal-backdrop" onClick={() => setActiveModal(null)}>
        <div className="modal-content" onClick={(e) => e.stopPropagation()}>
          <div className="modal-header">
            <h3>{modal.title}</h3>
            <button onClick={() => setActiveModal(null)}>&times;</button>
          </div>
          <div className="modal-body">{modal.content}</div>
        </div>
      </div>
    );
  };

  return (
    <>
      <header className="header">
        <div className="logo-section">
          <div className="logo-icon">
            <Activity size={20} />
          </div>
          <div>
            <span className="title">Rad-VQA</span>
            <span className="subtitle">AI Assistant</span>
          </div>
        </div>
        <nav className="main-nav">
          <a href="#" onClick={() => setActiveModal('about')}><Info size={16} /> About</a>
          <a href="#" onClick={() => setActiveModal('docs')}><FileText size={16} /> Docs</a>
          <a href="#" onClick={() => setActiveModal('warnings')}><AlertTriangle size={16} /> Warnings</a>
        </nav>
        <div className="controls-section">
          <div className="theme-switcher">
            <Palette size={16} />
            <select value={currentTheme} onChange={(e) => setCurrentTheme(e.target.value)}>
              {THEMES.map(theme => (
                <option key={theme} value={theme}>{theme.charAt(0).toUpperCase() + theme.slice(1)}</option>
              ))}
            </select>
          </div>
          <div className="status-section" data-connected={!!imageId}>
            {imageId ? <Sparkles size={14} /> : <Server size={14} />}
            <span>{imageId ? 'Connected' : 'Waiting'}</span>
          </div>
        </div>
      </header>
      {renderModal()}
    </>
  );
};

export default Header;